name: Build PR

on:
  pull_request:
    branches: ["main"]
    types: [ready_for_review, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # if: github.event.pull_request.draft == false
    name: Build PR
    runs-on: ubuntu-latest
    steps:
      - name: Ensure ready for review
        run: |
          if [ ${{ github.event.pull_request.draft }} == true ]; then
            # means we got a `synchronize` event for draft PR
            echo "::error ::Skipping Draft PR"
            exit 1
          fi

      - name: Build
        run: echo "Build success"
