name: Build Approved PR

on:
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.review.state == 'approved'
    name: Build Approved PR
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Build success"
