name: Build PR

on:
  pull_request:
    branches: ["main"]
    types: [ready_for_review, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Build PR
    runs-on: ubuntu-latest
    steps:
      - name: Sync build cache
        uses: actions/cache@v4.2.0
        with:
          key: ${{ github.ref }}
          restore-keys: |
            refs/pull/1
            refs/pull
          path: |
            build

      - name: Build
        run: |
          echo "ref =" ${{ github.ref }}
          echo "tree begin"
          tree -a
          echo "tree end"
          mkdir -p build && touch build/a
          echo "restored from cache =" `cat build/a`
          date > build/a
          echo "Build success"
